### ISSUE TITLE
seems to be walking base classes incorrectly sometimes?

### ISSUE THREAD

**Issue by grandinj** [PhilArmstrong/pahole-gdb#3]
It finds a hole because it seems to have walking the first two base classes in the wrong order:

/*   72     */ struct comphelper::OAnyEnumeration {
/* XXX 384 bit hole, try to pack */
/*  48    8 */    struct comphelper::OEnumerationLock comphelper::OEnumerationLock
/*   0   48 */    class comphelper::OAnyEnumeration_BASE comphelper::OAnyEnumeration_BASE
/* XXX 64 bit hole, try to pack */
/*  56    4 */    int m_nPos
/* XXX 32 bit hole, try to pack */
/*  64    8 */    class com::sun::star::uno::Sequence<com::sun::star::uno::Any> m_lItems
}

the code can be found here:
https://opengrok.libreoffice.org/xref/core/include/comphelper/enumhelper.hxx?r=12dce07a#102

**Comment by PhilArmstrong** [comment]
I’ve tried to re-create this with the current gdb / gcc releases and the code gets the offsets correct using the same pattern of templated base class. Do re-open if it’s still happening inside the libreoffice codebase + I’ll see if I can build that.

**Comment by grandinj** [comment]
thanks!
