### ISSUE TITLE
sometimes get zero size for base member

### ISSUE THREAD

**Issue by grandinj** [PhilArmstrong/pahole-gdb#4]
Could be template related

/*   80     */ struct comphelper::OPropertyArrayAggregationHelper {
/*   0    0 */    class cppu::IPropertyArrayHelper cppu::IPropertyArrayHelper
/* XXX 64 bit hole, try to pack */
/*   8   24 */    class std::vector<com::sun::star::beans::Property, std::allocator<com::sun::star::beans::Property> > m_aProperties
/*  32   48 */    class std::map<int, comphelper::internal::OPropertyAccessor, std::less<int>, std::allocator<std::pair<int const, comphelper::internal::OPropertyAccessor> > > m_aPropertyAccessors
}

code here:
    https://opengrok.libreoffice.org/xref/core/include/comphelper/propagg.hxx?r=376ee49f#92

**Comment by PhilArmstrong** [comment]
Ta. I’ll see if upstream has made any updates.

**Comment by PhilArmstrong** [comment]
nb. What version of gdb are you using?

**Comment by grandinj** [comment]
This is fedora29, and it report gdb 8.2-6

I'm on vacation now, but next week I can try stuff out if you need me to

**Comment by PhilArmstrong** [comment]
Ah, this is because the base class doesn’t contain any members at all, but you need the virtual pointer in order to access static member functions & virtual functions, so the entry in the struct is of non-zero size, despite not containing any fields.
We could probably return something more helpful here!

**Comment by PhilArmstrong** [comment]
I /think/ the current code gets this case correct, at least it does with my test-case that mirrors the libreoffice class structure.
Let me know if it still fails.
