### ISSUE TITLE
Structure size padding wrong?

### ISSUE THREAD

**Issue by leonid-s-usov** [PhilArmstrong/pahole-gdb#7]
If I'm reading the code correctly, there is a problem with structure size padding. It's assumed to always be divisible by 8, but that's not correct. The structure size is aligned to the maximum member size, not to 8 always

        # Check for padding at the end
        if endpos // 8 < atype.sizeof:
            hole = 8 * atype.sizeof - endpos

**Comment by PhilArmstrong** [comment]
endpos is counted in bits, whereas type.sizeof is measured in 8-bit chars. So this code correctly calculates the number of bits left between the last struct member and the end of the struct.

Unless I have misread it!

**Comment by leonid-s-usov** [comment]
Oh I see it now! 

My bad, I haven't read it correctly

**Comment by PhilArmstrong** [comment]
No worries!

Look at, eg
```
struct C { long int i; char a; };
struct D { char a; char b; char c; };

int main () {
  struct C c;
  struct D d;
}
```

and compare the pahole descriptions of structs C & D.

**Comment by leonid-s-usov** [comment]
I've really missed that the endpos is counted in bits, and then just wrongly assumed that the code is checking for an alignment to 8.
