### ISSUE TITLE
End padding comment shown in bits instead of bytes

### ISSUE THREAD

**Issue by leonid-s-usov** [PhilArmstrong/pahole-gdb#8]
https://github.com/PhilArmstrong/pahole-gdb/blob/66968ccee7a57f57248df3e1b3974a23d6050469/pahole.py#L85

Is it on purpose that the leftmost part of the comment about the struct padding is rendered in bits whereas it's always bytes in other cases at this position? I'd expect this to be showing bytes. 

If it's planned to show bits then maybe the format should be updated to make it clear.

The example on the main page (README) actually shows this issue

    /* XXX    5 */ !!  char [5] __40_bit_padding__
    ...
    /* XXX 1008 */ !!      char [126] __1008_bit_padding__
    ...
    /* XXX   60 */ !!    char [8] __60_bit_padding__

**Comment by PhilArmstrong** [comment]
Not particularly - this part of the code was a contributed patch IIRC.

**Comment by PhilArmstrong** [comment]
Indeed, this is clearly inconsistent. Let’s fix it up...

**Comment by PhilArmstrong** [comment]
Closed by 9f08af7d921edf2e35dd30feba8f8f2437844d45

**Comment by PhilArmstrong** [comment]
Closed by 677160a590774e8c3a49774d469ba1589707bdbf

**Comment by leonid-s-usov** [comment]
Need to update the README, too, with the fixed example

**Comment by PhilArmstrong** [comment]
True.

**Comment by leonid-s-usov** [comment]
(gdb) pahole testStruct walk
    /*  152     */ struct testStruct {
    /*   0    2 */     short a
    /*   2    1 */     char b
    /* XXX    5 */ !!  __40_bit_padding__
    /*   8  144 */     struct testStruct::more_struct {
    /*   0  128 */       union testStruct::more_struct::union_x {
    /*   0  128 */         char [128] c
    /*   0    2 */         struct testStruct::more_struct::union_x::s_y {
    /*   0    1 */           char v
    /*   1    0 */           char g1_1:7
    /* XXX    0 */ !!        __1_bit_padding__
                         } y
    /* XXX  126 */ !!      __1008_bit_padding__
                       } x
    /* 128    8 */       long e
    /* 136    0 */       char s1_1:1
    /* 136    0 */       char s1_2:1
    /* 136    0 */       char s2:2
    /* XXX    7 */ !!    __60_bit_padding__
                     } more
                   } testStruct

I think there are still multiple issues with the way padding is reported:

* that 126 padding inside the union is not correct, the union size is of the largest member and that padding is not correctly defined. If you change the order of the fields there will be no padding then?
* in case of bit maps, the total sum of sizes and padding doesn't match up to the struct size. See union x::y, it has size of 2 but both second char and the padding (1bit) are 0 bytes. Same about the final 60 bit padding, it resolves to 7 bytes which gives total sum of 143 instead of 144 for the `more_struct`
* closing braces offsets are not correct

**Comment by PhilArmstrong** [comment]
1) No, I think it will report the same regardless of order. It’s the potential lost space that’s being reported (in this case, the difference between a 2-char struct & a char[128]).
2) The struct size is recorded correctly, but bits are rounded down to the nearest char. If we count in chars, then it’s going to be wrong in one direction or the other here.
3) I’ll take a look at the offset calculation at some point. Patches welcome :)

**Comment by leonid-s-usov** [comment]
yes, I almost did that myself but then found out I have no gdb installed on my mac and couldn't get to it quickly.. I'll try to be more useful than just criticizing, I promise!
